name: Build and Release Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.SAMUEL_PAT2 }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Decode and write gcloud_key.json
        env:
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        run: echo $GCLOUD_KEY > gcloud_key.json

      - name: Parse version info from tag
        run: |
          VERSION=${GITHUB_REF:10}
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/remla2024-team9/model-service:${{ env.version }}
            ghcr.io/remla2024-team9/model-service:${{ env.version_major }}.${{ env.version_minor }}.latest
            ghcr.io/remla2024-team9/model-service:${{ env.version_major }}.latest
            ghcr.io/remla2024-team9/model-service:latest